import { JobListing } from '../types';

export const MOCK_JOBS: JobListing[] = [
  {
    id: '1',
    title: 'Senior React Developer',
    company: 'TechFlow Solutions',
    location: 'Remote',
    type: 'Full-time',
    salary: '$120k - $150k',
    description: 'We are looking for an experienced React developer to lead our frontend team. Must have experience with TypeScript, Tailwind, and Node.js.',
    requiredSkills: ['React', 'TypeScript', 'Node.js', 'Tailwind CSS'],
  },
  {
    id: '2',
    title: 'Product Designer',
    company: 'Creative Canopy',
    location: 'New York, NY',
    type: 'Hybrid',
    salary: '$90k - $120k',
    description: 'Join our design team to create intuitive and beautiful user experiences. Proficiency in Figma and Adobe Creative Suite is required.',
    requiredSkills: ['Figma', 'UI/UX', 'Prototyping', 'Adobe XD'],
  },
  {
    id: '3',
    title: 'Machine Learning Engineer',
    company: 'DataMinds AI',
    location: 'San Francisco, CA',
    type: 'On-site',
    salary: '$140k - $180k',
    description: 'Build the next generation of AI models. Experience with Python, PyTorch, and NLP is essential.',
    requiredSkills: ['Python', 'PyTorch', 'NLP', 'Machine Learning'],
  },
  {
    id: '4',
    title: 'Marketing Specialist',
    company: 'Growth Rocket',
    location: 'Austin, TX',
    type: 'Remote',
    salary: '$60k - $80k',
    description: 'Manage our social media channels and content strategy. Strong writing skills and familiarity with SEO tools needed.',
    requiredSkills: ['SEO', 'Content Marketing', 'Social Media', 'Copywriting'],
  },
  {
    id: '5',
    title: 'Backend Developer (Go)',
    company: 'StreamLine',
    location: 'Seattle, WA',
    type: 'Remote',
    salary: '$130k - $160k',
    description: 'Scale our microservices architecture using Go and Kubernetes.',
    requiredSkills: ['Go', 'Kubernetes', 'Docker', 'PostgreSQL'],
  },
];
